"""
Utilitaires pour sauvegarder et exporter les résultats.
"""

import json
import logging
from pathlib import Path
from typing import Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class SolutionExporter:
    """Exporte la solution générée dans différents formats"""
    
    def __init__(self, output_dir: str = "./outputs"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
    
    def export_all(self, solution: dict, project_name: str = "project") -> dict:
        """Exporte la solution complète"""
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        project_dir = self.output_dir / f"{project_name}_{timestamp}"
        project_dir.mkdir(exist_ok=True)
        
        files_created = {}
        
        # Export JSON des artefacts
        files_created['summary'] = self._export_summary(solution, project_dir)
        files_created['metrics'] = self._export_metrics(solution, project_dir)
        
        # Export individuels des artefacts
        if 'artifacts' in solution:
            artifacts = solution['artifacts']
            
            if artifacts.get('architecture'):
                files_created['architecture'] = self._save_file(
                    project_dir / "ARCHITECTURE.md",
                    self._format_architecture(artifacts['architecture'])
                )
            
            if artifacts.get('code'):
                files_created['code'] = self._save_file(
                    project_dir / "CODE.md",
                    artifacts['code']
                )
            
            if artifacts.get('tests'):
                files_created['tests'] = self._save_file(
                    project_dir / "TESTS.md",
                    artifacts['tests']
                )
            
            if artifacts.get('documentation'):
                files_created['documentation'] = self._save_file(
                    project_dir / "DOCUMENTATION.md",
                    artifacts['documentation']
                )
        
        logger.info(f"✅ Solution exportée dans: {project_dir}")
        logger.info(f"   Fichiers créés: {len(files_created)}")
        
        return {
            "output_dir": str(project_dir),
            "files": files_created,
            "timestamp": timestamp
        }
    
    def _export_summary(self, solution: dict, output_dir: Path) -> str:
        """Exporte un résumé JSON"""
        summary = {
            "status": solution.get('status'),
            "score": solution.get('score'),
            "iteration": solution.get('iteration'),
            "generated_at": datetime.now().isoformat()
        }
        
        filepath = output_dir / "SUMMARY.json"
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(summary, f, indent=2, ensure_ascii=False)
        
        return str(filepath)
    
    def _export_metrics(self, solution: dict, output_dir: Path) -> str:
        """Exporte les métriques détaillées"""
        metrics_file = output_dir / "METRICS.json"
        
        with open(metrics_file, 'w', encoding='utf-8') as f:
            json.dump(solution.get('metrics', []), f, indent=2)
        
        return str(metrics_file)
    
    def _format_architecture(self, content: str) -> str:
        """Formate le contenu architecture avec header"""
        header = """# Architecture System

Generated by Multi-Agent System
"""
        return header + "\n" + content
    
    def _save_file(self, filepath: Path, content: str) -> str:
        """Sauvegarde un fichier"""
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            logger.debug(f"  ✓ {filepath.name}")
            return str(filepath)
        except Exception as e:
            logger.error(f"  ✗ Erreur sauvegarde {filepath}: {e}")
            return ""


class ReportGenerator:
    """Génère des rapports lisibles"""
    
    @staticmethod
    def generate_text_report(solution: dict) -> str:
        """Génère un rapport texte"""
        
        report = f"""
╔════════════════════════════════════════════════════════════╗
║         RAPPORT SYSTÈME MULTI-AGENTS AUTO-CORRECTIF        ║
╚════════════════════════════════════════════════════════════╝

📊 RÉSUMÉ EXÉCUTION
─────────────────
Status: {solution.get('status', 'N/A')}
Score final: {solution.get('score', 0):.1f}%
Itération optimale: {solution.get('iteration', 0)}

📈 MÉTRIQUES
──────────
"""
        
        if 'metrics' in solution and solution['metrics']:
            report += f"\nItérations exécutées: {len(solution['metrics'])}\n"
            
            # Dernière itération
            last_metric = solution['metrics'][-1]
            report += f"""
Dernière itération:
  • Score global: {last_metric.get('overall_score', 0):.1f}%
  • Qualité code: {last_metric.get('reviewer_score', 0):.1f}%
  • Sécurité: {last_metric.get('security_score', 0):.1f}%
  • Problèmes: {last_metric.get('issues_count', 0)}
"""
        
        report += f"""

🎯 LIVRABLES
────────────
✓ Architecture système
✓ Code complet et fonctionnel
✓ Suite de tests unitaires
✓ Audit sécurité
✓ Documentation complète

📦 ARTEFACTS GÉNÉRÉS
────────────────────
• ARCHITECTURE.md - Design et patterns
• CODE.md - Implémentation
• TESTS.md - Suite de tests
• DOCUMENTATION.md - Guide complet
• METRICS.json - Métriques détaillées

"""
        
        return report
    
    @staticmethod
    def generate_html_report(solution: dict) -> str:
        """Génère un rapport HTML"""
        
        score = solution.get('score', 0)
        iteration = solution.get('iteration', 0)
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Rapport Multi-Agents</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }}
        .container {{ background: white; padding: 20px; border-radius: 8px; max-width: 1000px; }}
        h1 {{ color: #333; border-bottom: 3px solid #007bff; padding-bottom: 10px; }}
        .metric {{ display: inline-block; margin: 10px 20px 10px 0; }}
        .score {{ font-size: 32px; font-weight: bold; color: #007bff; }}
        .progress {{ width: 100%; height: 30px; background: #ddd; border-radius: 5px; overflow: hidden; }}
        .progress-bar {{ height: 100%; background: #28a745; width: {score}%; }}
        .status-ok {{ color: #28a745; font-weight: bold; }}
        .status-warning {{ color: #ffc107; font-weight: bold; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🤖 Rapport Système Multi-Agents</h1>
        
        <div class="metric">
            <div>Score Final</div>
            <div class="score">{score:.1f}%</div>
        </div>
        
        <div class="metric">
            <div>Itération</div>
            <div class="score">{iteration}</div>
        </div>
        
        <h2>Progression Qualité</h2>
        <div class="progress">
            <div class="progress-bar"></div>
        </div>
        
        <h2>Artefacts Générés</h2>
        <ul>
            <li>✓ Architecture système</li>
            <li>✓ Code fonctionnel</li>
            <li>✓ Tests unitaires</li>
            <li>✓ Audit sécurité</li>
            <li>✓ Documentation</li>
        </ul>
        
        <p style="color: #666; margin-top: 30px;">
            Généré par Multi-Agent System • {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}
        </p>
    </div>
</body>
</html>"""
        
        return html


class Dashboard:
    """Tableau de bord en temps réel"""
    
    @staticmethod
    def display_dashboard(orchestrator) -> str:
        """Affiche un dashboard actualisable"""
        
        dashboard = f"""
╔════════════════════════════════════════════════════════════╗
║          🚀 SYSTÈME MULTI-AGENTS EN EXÉCUTION              ║
╚════════════════════════════════════════════════════════════╝

📍 ÉTAT ACTUALISÉ
{datetime.now().strftime('%d/%m/%Y %H:%M:%S')}

📊 PROGRESSION
──────────────
Itération: {orchestrator.iteration_count}/{orchestrator.max_iterations}

Meilleur score: {orchestrator.best_score:.1f}%
{"█" * int(orchestrator.best_score / 5) + "░" * (20 - int(orchestrator.best_score / 5))}

🤖 AGENTS ACTIFS
────────────────
"""
        
        for name, agent in orchestrator.agents.items():
            dashboard += f"  • {agent}\n"
        
        if orchestrator.metrics_history:
            last_metric = orchestrator.metrics_history[-1]
            dashboard += f"""

📈 DERNIÈRE ITÉRATION
─────────────────────
Score global: {last_metric.overall_score:.1f}%
Qualité: {last_metric.reviewer_score:.1f}%
Sécurité: {last_metric.security_score:.1f}%
Problèmes: {last_metric.issues_count}
"""
        
        return dashboard
